# Generated by Django 2.1.5 on 2019-01-14 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=200)),
                ('animal_race', models.CharField(max_length=200)),
                ('animal_type', models.CharField(max_length=200)),
                ('animal_etat', models.CharField(max_length=200)),
                ('animal_lieu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement_id', models.CharField(max_length=200)),
                ('disponibilite', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalerie.Animaux')),
            ],
        ),
    ]
