# Generated by Django 2.1.5 on 2019-01-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='animal',
        ),
        migrations.AlterField(
            model_name='animaux',
            name='animal_lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalerie.Equipement'),
        ),
    ]
